config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users, only: :show
  resources :stocks, only: [:show, :edit, :create, :update, :destroy]
  get 'users/sign_out' => 'devise/sessions#destroy'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@stock = Stock.new()
	end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /stocks/1
  def show
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  def create
    @stock = Stock.new(stock_params)
    @stock.user = current_user
    if @stock.save
      redirect_to @user, notice: "#{@stock.symbol} was added to your stocks."
    else
      @errors = @stock.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /stocks/1
  def update
    if @stock.update(stock_params)
      redirect_to @user, notice: "#{@stock.symbol} was successfully updated."
    else
      @errors = @stock.errors.full_messages
      render :edit
    end
  end

  # DELETE /stocks/1
  def destroy
    @stock.destroy
    redirect_to @user, notice: "#{@stock.symbol} was removed from your stocks"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:name,:symbol) 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, :redirect_unless_owner_of_page_is_current_user

	def show
		userstocks = @user.stocks
		@stocks = userstocks.paginate(:page => params[:page], :per_page => 10)
	end

private
	
	def find_user
		@user = User.find(params[:id])
	end

	def redirect_unless_owner_of_page_is_current_user
		unless current_user == @user
			@errors = ["You may only view your own profile"]
			render 'home/index'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h4>Quick Lookup</h4>

<div class="row">
	<div class="col-12-sm">
		<form class="well form-inline" id="searchform">
			<input type="text" id="symbolsearch" class="input-" placeholder="Company Name or Symbol">
			<span id="loading" class="help-inline hide"><%= image_tag 'spinner.gif' %> Loading...</span>
		</form>
	</div>
</div>

<div id="selected-stock-data" class="hide container">
	<span id="alert" class="help-inline label label-info"></span>
	<div class="row">
		<div class="col-xs-12">
			<span id="selected-symbol-price" class="hide h2"></span><span id='quoteChange'></span>
		</div>
	</div>
	
	<% if current_user %>
	<div class="row">
		<div class="col-xs-12">			
			<%= form_for @stock,{id: "add"} do |f| %>
				<div id="add"></div>
				<%= f.submit 'Add to Portfolio', {class: "btn btn-success", id: "add-stock-btn"} %>
			<% end %>
		</div>
	</div>	<!-- /row-->
	<% end %>

	<div class="row">
		<div class="col-xs-12">
			<small id="selected-name" class="hide"></small>	
			<table>
				<tr>
					<td>Previous Close</td>
					<td id="selected-PreviousClose"></td>
				</tr>
				<tr>
					<td>Today's High/low</td>
					<td id="selected-todayHighLow"></td>
				</tr>
				<tr>
					<td>52-week High/low</td>
					<td id="selected-yearlyHighLow"></td>
				</tr>
				<tr>
					<td>Daily Avg. Volume</td>
					<td id="selected-AverageDailyVolume"></td>
				</tr>
			</table>
		</div>	<!-- /row-->
	</div> <!-- /selected-stock-data -->
	<div class="row">
		<div class="col-xs-12">
			<div id='viz'></div>
		</div>
	</div>	<!-- /row-->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Stocktracker</title>
	<script src="//d3plus.org/js/d3.js"></script>
	<script src="//d3plus.org/js/d3plus.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">StockTracker</a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
    	<li><a href="/users/<%= current_user.id %>">My Account</a></li>
      <li><%= link_to('Sign Out', '/users/sign_out', html_options = {method: :delete})%></li>
    	<% else %>
    	<li><a href="users/sign_in">Sign In</a></li>
    	<% end %>
    </ul>
    
    <ul class="dropdown-menu">
      <% if current_user %>
      <li><a href="/users/<%= current_user.id %>"></a></li>
      <% else %>
      <li><a href="users/sign_in">Sign In</a></li>
      <% end %>
    </ul>
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', user_path(current_user) %>


<div id="selected-stock-data" class="container">
	<span id="alert" class="help-inline label label-info"></span>
	
	<div class="row">
		<div class="col-xs-9">
			<span id="selected-symbol-price" class="h2"><%= @stock.symbol %></span><span id='quoteChange'></span>
		</div>
		<div class="col-xs-3">
		</div>
	</div>	<!-- /row-->

	<div class="row">
		<div class="col-xs-12">
			<small id="selected-name"></small>	
			<table>
				<tr>
					<td>Previous Close</td>
					<td id="selected-PreviousClose"></td>
				</tr>
				<tr>
					<td>Today's High/low</td>
					<td id="selected-todayHighLow"></td>
				</tr>
				<tr>
					<td>52-week High/low</td>
					<td id="selected-yearlyHighLow"></td>
				</tr>
				<tr>
					<td>Daily Avg. Volume</td>
					<td id="selected-AverageDailyVolume"></td>
				</tr>
			</table>
		</div>	<!-- /row-->
	</div> <!-- /selected-stock-data -->
	<div class="row">
		<div class="col-xs-12">
			<div id='viz'></div>
		</div>
	</div>	<!-- /row-->
</div>
<script type="text/javascript">
	$IndexQuickLookupAndRender("<%= @stock.symbol %>")
</script>

app/views/users/show.html.erb
<p>This is the Users Show page for User #<%= @user.id %>.</p>

<%if notice %>
	<p id="notice" class="bg-success"><%= notice %></p>
<% end %>

<% if @errors %>
  <div id="error_explanation">
    <h2 class="bg-warning"><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>
  	<ul>
    	<% @errors.each do |message| %>
				<li class="bg-danger"><%= message %></li>
   		<% end %>
    </ul>
  </div>
<% end %>

<p>Email: <%= @user.email %></p>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

<% @stocks.each do |stock| %>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h3 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=stock.symbol%>" aria-expanded="true" aria-controls="collapse<%=stock.symbol%>">
          <%= stock.symbol %>
        </a>
      </h3>
    </div>

    <div id="collapse<%= stock.symbol %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">

			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<span id="" class="selected-symbol<%= stock.symbol %> hide h2"></span><span class='quoteChange<%= stock.symbol %>'></span>

					</div>
				</div>	<!-- /row-->

				<div class="row">
					<div class="col-xs-12">
						<small class="selected-name<%= stock.symbol %>"></small>	
						<table>
							<tr>
								<td>Previous Close</td><td class="selected-PreviousClose<%= stock.symbol %>"></td>
							</tr>
							<tr>
								<td>Today's High/low</td><td class="selected-todayHighLow<%= stock.symbol %>"></td>
							</tr>
							<tr>
								<td>52-week High/low</td><td class="selected-yearlyHighLow<%= stock.symbol %>"></td>
							</tr>
							<tr>
								<td>Daily Avg. Volume</td><td class="selected-AverageDailyVolume<%= stock.symbol %>"></td>
							</tr>
						</table>
						<%= link_to('Remove from Portfolio', "/stocks/#{stock.id}", html_options = {method: :delete})%>
					</div>	<!-- /row-->
				</div> <!-- /selected-stock-data -->
				<script type="text/javascript">
					$UserShowQuickLookupAndRender("<%= stock.symbol %>")
				</script>			  
      </div>
    </div>
  </div>
</div>

<% end %>
</div>
<%= will_paginate @stocks %>